// GENERATED CODE -- DO NOT EDIT! 
$group("datas");
cc.app.datas.shop = {
    "Sheet1": [
        {
            "id": 0,
            "iconid": 6,
            "price": 99.99,
            "rawprice": 199.99,
            "rawcoin": 7000000,
            "vipp": 600,
            "expiconid": 2,
            "coinIconMul": 2,
            "muliconid": 1,
            "vippoint": 10000,
            "hoticonid": 2,
            "txtad": "+ADS  FREE",
            "buffid": 2,
            "gpid": "a.coin.99.99",
            "type": 1,
            "backReward": 840000000
        },
        {
            "id": 1,
            "iconid": 5,
            "price": 49.99,
            "rawprice": 99.99,
            "rawcoin": 1500000,
            "vipp": 500,
            "expiconid": 1,
            "coinIconMul": 2,
            "muliconid": 1,
            "vippoint": 5000,
            "hoticonid": 1,
            "txtad": "+ADS  FREE",
            "buffid": 1,
            "gpid": "a.coin.49.99",
            "type": 1,
            "backReward": 150000000
        },
        {
            "id": 2,
            "iconid": 4,
            "price": 24.99,
            "rawprice": 49.99,
            "rawcoin": 450000,
            "vipp": 400,
            "expiconid": 0,
            "coinIconMul": 1,
            "muliconid": 0,
            "vippoint": 2500,
            "hoticonid": 0,
            "txtad": "+ADS  FREE",
            "buffid": 0,
            "gpid": "a.coin.24.99",
            "type": 1,
            "backReward": 20000000
        },
        {
            "id": 3,
            "iconid": 3,
            "price": 14.99,
            "rawprice": 29.99,
            "rawcoin": 200000,
            "vipp": 300,
            "expiconid": 0,
            "coinIconMul": 1,
            "muliconid": 0,
            "vippoint": 1500,
            "hoticonid": 0,
            "txtad": "+ADS  FREE",
            "buffid": 0,
            "gpid": "a.coin.14.99",
            "type": 1,
            "backReward": 6000000
        },
        {
            "id": 4,
            "iconid": 2,
            "price": 4.99,
            "rawprice": 9.99,
            "rawcoin": 40000,
            "vipp": 200,
            "expiconid": 0,
            "coinIconMul": 1,
            "muliconid": 0,
            "vippoint": 500,
            "hoticonid": 0,
            "txtad": "+ADS  FREE",
            "buffid": 0,
            "gpid": "a.coin.4.99",
            "type": 1,
            "backReward": 800000
        },
        {
            "id": 5,
            "iconid": 1,
            "price": 1.99,
            "rawprice": 3.99,
            "rawcoin": 12000,
            "vipp": 100,
            "expiconid": 0,
            "coinIconMul": 1,
            "muliconid": 0,
            "vippoint": 200,
            "hoticonid": 0,
            "txtad": "+ADS  FREE",
            "buffid": 0,
            "gpid": "a.coin.1.99",
            "type": 1,
            "backReward": 120000
        },
        {
            "id": 6,
            "iconid": 1,
            "price": 19.99,
            "rawprice": 19.99,
            "rawcoin": 300000,
            "vipp": 100,
            "expiconid": 0,
            "coinIconMul": 1,
            "muliconid": 0,
            "vippoint": 1000,
            "hoticonid": 0,
            "txtad": " ",
            "buffid": 0,
            "gpid": "a.coin.19.99",
            "type": 2,
            "backReward": 18000000
        }
    ]
}